apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    name: {{ include "name" . }}
    app: {{ include "name" . }}
    app.kubernetes.io/name: prometheus-operator
spec:
  selector:
    app: {{ include "name" . }}
    release: {{ .Release.Name }}
  ports:
  
    - name: http
      port: 80
      targetPort: 9086
  type: {{ .Values.service.type }}
