apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-test-servicemonitor
  namespace: monitoring
  labels:
    name: python-test-servicemonitor
spec:
  selector:
    matchLabels:
      app: python-test
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http